# SITE CONFIGURATION
baseurl: ""
url: "http://www.proofof.blog"
title: Proof of Blog
description: "An ongoing chain of word-based proof of blog." # used by search engines


avatar: assets/img/icon.png
favicon: assets/favicon.ico

# Header and footer text
header_text: > #two or three lines to describe your site
     <p>An ongoing chain of word-based proof of blog</p>
header_text_feature_image: assets/img/pexels/triangular.jpeg
  footer_text: >
    Thank you for your time.

  # Scripts / Features 
  google_analytics: UA-120210782-1 # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: proofofblog
  katex: true # Enable if using math markup
  
  special_page:
    search: 
      icon: "search" # Assuming page link and icon are the same
      enabled: true
    tags:
      icon: "tags"
      enabled: true


# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
cookie_consent: false                                   # To respect the usage of cookies
layout_variables:                                       # Open the "_sass > base" folder, and open "_variables.scss"
footer_icons:                                           # In _data/social.yml
share_buttons:                                          # In _data/social.yml
authors:                                                # In _data/authors.yml
language:                                               # In _data/language.yml

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
